### ISSUE TITLE
Collaboration with XND

### ISSUE THREAD

**Issue by teoliphant** [numpy/numpy-stubs#17]
The same ideas being pursued here could also be applied to the more extensive ndtypes for xnd containers that are being currently developed at https://github.com/plures/xnd

We are currently getting a computation system built that would allow defining functions on (farily) arbitrary typed containers.  

We are also working with the Numba team to get support for xnd in Numba.

I just want to ensure that the work done here is aware of our efforts in xnd.   The XND project is open and eager for any input from folks interested in typed containers with Python.

**Comment by person142** [comment]
IIUC, collaboration is probably more on the new dtypes side of thing (NEP 41 et. al.); IIRC there was some discussion on the mailing list at least tangentially related to this. For the type stubs specifically we will really just be following the path that NEP 41 blazed.
