### ISSUE TITLE
Continuous integration tests

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy-stubs#3]
What should these look like?

At the least, we probably should verify that mypy can successfully type-check some simple examples using these type annotations.

**Comment by henryJack** [comment]
Happy to write the example annotated code once the stubs are done. It's probably best to add a mypy job to the pipeline with multiple scripts testing that mypy passes and throws errors where it's supposed to.

**Comment by eric-wieser** [comment]
I'm workin on #2, and I'm not even sure I'm able to test this locally - it seems `mypy` doesn't support `_stubs` packages yet.

**Comment by shoyer** [comment]
It seems that we are very cutting edge here in relying on PEP 561. @ethanhs is still finishing up the mypy implementation in https://github.com/python/mypy/pull/4278, but I guess we could test locally against his branch.

**Comment by shoyer** [comment]
See https://github.com/python/typeshed/issues/754 and https://github.com/python/typeshed/issues/1339. It seems like tests for stubs make sense for at least tricky cases, but are probably overkill when required for everything.

**Comment by eric-wieser** [comment]
We're probably going to want to use whatever mypy is using to run its own tests here. Perhaps to support PEP561, mypy should extract its testing module to be standalone

**Comment by ethanhs** [comment]
The branch is in a somewhat limited state, it checks against packages installed only for the Python mypy is installed in. Just a heads up. It should work for the simple case.

**Comment by shoyer** [comment]
We have this now.
