### ISSUE TITLE
Want to contribute to project

### ISSUE THREAD

**Issue by theodoretliu** [numpy/numpy-stubs#35]
Hi, I'm a student working on a thesis right now, and my proposal is to add dependent typing to Python and numpy in particular. I don't know if this is the right place to post or ask about this, but I want to ultimately contribute directly to numpy, python, and mypy and this seemed like an appropriate place. Specifically, I want to extend this project and be able to reject statically
```python
x = np.zeros((1, 2))
x @ x
```
and accept
```python
x @ x.T
```
Would this be the right place to discuss syntax, necessary work, and other things required to make this a reality?

**Comment by ethanhs** [comment]
Hi, it'd be great to have someone work on this effort! There is some discussion here: https://github.com/python/typing/issues/513

Also at the last typing summit there was discussion of type system features for pytorch. I think bringing this up on `typing-sig@python.org` is probably the best place to introduce yourself to the relevant people.

**Comment by theodoretliu** [comment]
Thank you for the information! I'll also respond on the thread you linked and shoot an email to the mailing list.
