### ISSUE TITLE
How do you use this package?

### ISSUE THREAD

**Issue by geiszla** [numpy/numpy-stubs#40]
I can't find any information on how to install this package to a local workspace. I tried installing the git repo via pip, but mypy still complains when I try to use it (`"ndarray" expects no type arguments, but 1 given`). I know this is an experimental project, but can I use the parts that are done so far?

**Comment by mikolajz** [comment]
FWIW it works for me when install by pip from git repo. Maybe if you included a short snippet of code that doesn't work for you? Then we could check if it works for others.

**Comment by person142** [comment]
Yes, installing from the repo is the only way to use the stubs for now. From your particular error it sounds like you are trying to do something like `ndarray[np.int64]`, which is not supported yet. See e.g. https://github.com/numpy/numpy-stubs/issues/7 and https://github.com/numpy/numpy-stubs/pull/48 for more context.

**Comment by person142** [comment]
(Closing as I believe the question has been answered.)
