### ISSUE TITLE
Not supported: np.float32() can accept a list and produce an ndarray

### ISSUE THREAD

**Issue by mikolajz** [numpy/numpy-stubs#41]
The following code works but doesn't pass type checking:
```
x = None  # type: Optional[np.ndarray]
x = np.float32([1.0, 0.0, 0.0])
assert isinstance(x, np.ndarray)
```

But I don't know if this can be expressed in mypy  - when I tried adding `@overload  def __new__(cls, x: List[float]) -> ndarray: ...`, mypy now accepted the arguments but ignored the return type and assumed this produces an np.float32.

**Comment by person142** [comment]
After discussion on the mailing list:

https://mail.python.org/pipermail/numpy-discussion/2020-April/080566.html

I think we've decided that we want to discourage such uses and instead encourage people to write

```python
np.array([1.0, 0.0, 0.0], dtype=np.float32)
```

I've opened https://github.com/numpy/numpy-stubs/pull/61 to clarify that intent.

**Comment by mikolajz** [comment]
Makes sense.
