### ISSUE TITLE
conda distribution

### ISSUE THREAD

**Issue by analog-cbarber** [numpy/numpy-stubs#68]
Given that this project doesn't look like it is going to get merged into numpy any time soon, it would be really nice if there were a conda distribution of the package on `conda-forge` or some other appropriate channel.

**Comment by rgommers** [comment]
There was consensus on merging it into NumPy soonish. There's also no PyPI package; for now you need to install directly from this repo, and it will be available in NumPy probably later this year.

It moves too fast right now, so creating a separate package doesn't make sense.

**Comment by person142** [comment]
Going to close this since I think the issue has been resolved. As Ralf mentions, keep an eye out in future NumPy releases!

**Comment by analog-cbarber** [comment]
I pushed a conda.recipe to the conda branch of my fork in case anyone else wants to use it:

https://github.com/analog-garage/numpy-stubs/tree/conda/conda.recipe
