### ISSUE TITLE
Don't allow initializing `generic`

### ISSUE THREAD

**Issue by person142** [numpy/numpy-stubs#77]
Follow up to https://github.com/numpy/numpy-stubs/issues/72.

The following currently passes mypy:

```python
import numpy as np

reveal_type(np.generic(1))
```

but you can't actually create instances of `generic`:

```python
>>> import numpy as np
>>> np.generic(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot create 'numpy.generic' instances
```

We should

- Add constructors specifically to the classes that can be instantiated (`np.float64` etc)
- Remove the constructor from `generic`

**Comment by BvB93** [comment]
The same issue seems to apply to ``np.number`` and ``np.complexfloating``:

``` python
>>> import numpy as np

>>> np.number(1)
Traceback (most recent call last):
   ...
TypeError: cannot create 'numpy.number' instances

>>> np.complexfloating(1)
Traceback (most recent call last):
   ...
TypeError: cannot create 'numpy.complexfloating' instances
```

**Comment by BvB93** [comment]
I've created a pull request addressing the issue at https://github.com/numpy/numpy-stubs/pull/80.

**Comment by person142** [comment]
Closed by https://github.com/numpy/numpy-stubs/pull/80.
