### ISSUE TITLE
Unimplemented stubs for certain top-level methods

### ISSUE THREAD

**Issue by Safeturn** [numpy/numpy-stubs#84]
If I am not mistaken, many methods like `np.sum`, `np.cumsum`, `np.mean` and `np.append` do not have stubs yet. Is there any particular reason / caveat because of which these methods have not yet been implemented or has it simply not happened yet?

**Comment by person142** [comment]
Just hasn’t happened yet; see e.g. https://github.com/numpy/numpy-stubs/issues/54.

Right now we are more focused on moving what we have into NumPy itself as discussed in https://github.com/numpy/numpy-stubs/issues/79.
