### ISSUE TITLE
Plan for migrating the stubs to NumPy

### ISSUE THREAD

**Issue by person142** [numpy/numpy-stubs#87]
These are the things I'm planning on doing to merge the stubs into NumPy:

- Get https://github.com/numpy/numpy-stubs/pull/80 merged
- Move the tests to NumPy. That way we can keep running them during the migration.
- Add the new `numpy.typing` module
- Move all the stubs over
- Get the tests hooked up to CI

Please raise any concerns here.

**Comment by person142** [comment]
Well, no plan survives contact with the enemy, and it turned out to be hard to port the tests and stubs separately... so I did them both at the same time: https://github.com/numpy/numpy/pull/16515

**Comment by person142** [comment]
Still need to add the typing module at runtime, but by and large... migration complete!

**Comment by rgommers** [comment]
Awesome, thanks @person142 and everyone else who contributed!
