### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by person142** [numpy/numpy-stubs#89]
https://github.com/numpy/numpy-stubs/pull/88 updates the README to point contributors/users to NumPy, now we should archive this repo.

I don't have permissions to do this; @rgommers (or anybody with sufficient permissions) could you do the honors?

**Comment by rgommers** [comment]
Before doing that, it would probably make sense to migrate still-relevant issues to the main repo, close other issues and PRs. Everything becomes read-only after archiving.

Does that make sense @person142?

**Comment by person142** [comment]
Makes sense, I've migrated or closed all issues and closed old PRs, so we should be ready to go now.

**Comment by rgommers** [comment]
Thanks Josh! I'll archive now. Closing this issue first, since doing it the other way around isn't possible.
